CREATE DATABASE IF NOT EXISTS tacoya_db;
USE tacoya_db;

DROP TABLE tacos;

CREATE TABLE IF NOT EXISTS tacos (
	id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    taco_name VARCHAR(50) NOT NULL,
	shell VARCHAR(50) NOT NULL DEFAULT 'Flour',
    vegetarian BOOlEAN DEFAULT 0 NOT NULL,
    picked_up DEFAULT 0 BOOLEAN
);